"""
Rota Fortunae — economy objects (OOP scaffolding), LAND-based model.

New economic model (design doc `Rota Fortunae_ Civilizations.txt`): a simplified, higher-detail economy.
The productive unit is LAND (no more districts / tier chains). Each location holds land in three states:

    Pastoral   — the DEFAULT land (unused/destroyed land reverts to it). Small food+wealth surplus, no upkeep.
    Cultivated — large food + moderate wealth; has capital upkeep (stubbed this pass).
    Urban      — lots of wealth + Consumables, NO food; heavy capital upkeep (stubbed).

Three pop types: Slave / Commoner / Elite. Three goods: Food / Consumables / Wealth.

Simplifications this pass: **all land is elite-owned** (no subsistence / worker-owned land — that was a
holdover). Capital is a stub multiplier on output (real invest/upkeep/depreciation deferred). Land
conversion, migration, location tiers, the state elite-opportunity pool, and the consumables->urban-output
feedback are DEFERRED (tracked read-outs added in their own increments).

NO GDP anywhere (see economy_design.md): Wealth is a value generated by land (surplus / tax base), never
negative; a pop's *share* can be 0. Below-subsistence shows up as a FOOD shortage, not negative wealth.
Pop wealth is a MONTHLY RUNNING TOTAL (this tick's income), overwritten each tick — only treasuries
accumulate. All wage/output/wealth math lives in extra_functions.py and is reused here.
"""

from extra_functions import (
    get_wealth_level, get_shortage_modifier,
    get_wage_share, get_job_capacity, get_output, get_job_pull,
    wealth_req, food_req, goods_req,
)


# ---------------------------------------------------------------------------
# Land type (shared archetype — the kind of land, no tiers)
# ---------------------------------------------------------------------------
class LandType:
    """A state of land. Defines its per-worker OUTPUT distribution over the three goods
    (food / consumables / wealth) plus labor/footprint/elite-opportunity coefficients. No tier chains:
    technology later scales `capital` (a per-parcel multiplier), it does not swap the type."""

    def __init__(self, name, category, outputs,
                 labor_per_area=1.0, land_per_area=1.0,
                 saturation=1.0, exp=1.0,
                 elite_opps_per_area=0.0, security_exposure=1.0,
                 capital_weight=1.0, produces_food=True):
        self.name = name
        self.category = category                 # 'cultivated' | 'pastoral' | 'urban'
        self.outputs = dict(outputs)             # good -> base productivity per worker
        self.labor_per_area = labor_per_area     # job capacity per unit area
        self.land_per_area = land_per_area       # land footprint per unit area
        self.saturation = saturation             # get_output saturation param
        self.exp = exp                           # get_output exponent
        self.elite_opps_per_area = elite_opps_per_area   # elite ownership/mgmt slots per area
        self.security_exposure = security_exposure       # value lost when security drops (stub hook)
        self.capital_weight = capital_weight     # how strongly the capital stub scales this land (stub hook)
        self.produces_food = produces_food

    def __repr__(self):
        return f"LandType({self.name}, {self.category}, out{list(self.outputs)})"


# ---------------------------------------------------------------------------
# Concrete land types (per the doc's land descriptions)
# ---------------------------------------------------------------------------
# Pastoral: the DEFAULT land. Small food + wealth surplus, cheap, no upkeep, low elite opportunity.
PASTORAL = LandType(
    "Pastoral", "pastoral", {"food": 1.2, "wealth": 0.3},
    labor_per_area=1.0, land_per_area=1.0, elite_opps_per_area=0.010,
    security_exposure=0.5, capital_weight=0.3,
)

# Cultivated: large food + moderate wealth; capital upkeep (stub). The staple productive land.
CULTIVATED = LandType(
    "Cultivated", "cultivated", {"food": 2.5, "wealth": 1.0},
    labor_per_area=1.0, land_per_area=1.0, elite_opps_per_area=0.020,
    security_exposure=1.0, capital_weight=1.0,
)

# Urban: lots of wealth + Consumables, NO food. Heavy upkeep (stub); most elite opportunity.
URBAN = LandType(
    "Urban", "urban", {"wealth": 3.0, "consumables": 2.0},
    labor_per_area=1.0, land_per_area=1.0, elite_opps_per_area=0.030,
    security_exposure=1.5, capital_weight=1.5, produces_food=False,
)

LAND_TYPES = {lt.name: lt for lt in (PASTORAL, CULTIVATED, URBAN)}


# ---------------------------------------------------------------------------
# Parcel (instance: a quantity of one land type in a location; always elite-owned)
# ---------------------------------------------------------------------------
class Parcel:
    """A quantity of land of one type, worked this tick. `area` scales jobs/output/footprint; `capital` is
    a STUB multiplier (real Rural/Urban capital flows come later). Always owned by an Elite pop."""

    def __init__(self, land_type: LandType, area=1.0, capital=1.0, owner=None):
        self.land_type = land_type
        self.area = float(area)
        self.capital = float(capital)      # stub multiplier on effective jobs/output
        self.owner = owner                 # Elite Pop that owns this land
        self.workers = 0.0                 # labor assigned this tick (set by the location's allocator)

    # --- capacity / footprint -------------------------------------------------
    def job_capacity(self):
        return get_job_capacity(self.land_type.labor_per_area * self.area * self.capital)

    def land_use(self):            return self.land_type.land_per_area * self.area
    def elite_opportunities(self): return self.land_type.elite_opps_per_area * self.area

    # --- labor market ---------------------------------------------------------
    def job_pull(self, wage_share, pull_factor=1.0):
        """How strongly this parcel pulls workers (weighted by pay). Summed across parcels to split labor."""
        return get_job_pull(self.job_capacity(), wage_share, pull_factor)

    # --- production -----------------------------------------------------------
    def produce(self):
        """{good: amount produced} — per-worker base scaled by labor (saturating with jobs/worker)."""
        jobs = self.job_capacity()
        return {g: get_output(jobs, self.workers, base, self.land_type.saturation, self.land_type.exp)
                for g, base in self.land_type.outputs.items()}

    def __repr__(self):
        return (f"Parcel({self.land_type.name} area={self.area:.1f} cap={self.capital:.1f} "
                f"workers={self.workers:.2f})")


# ---------------------------------------------------------------------------
# Pop (a group of people of one type & civilization in a location)
# ---------------------------------------------------------------------------
class Pop:
    TYPES = ("Slave", "Commoner", "Elite")

    def __init__(self, pop_type, amount, civ="default", wealth=0.0):
        assert pop_type in self.TYPES, pop_type
        self.pop_type = pop_type
        self.civ = civ
        self.amount = float(amount)
        # Wealth is a MONTHLY RUNNING TOTAL (this tick's income), not an accumulating stock. >= 0.
        self.wealth = float(wealth)
        # Standard-of-living inputs, refreshed by the location each tick:
        self.food_access = 1.0          # fraction of food need met
        self.goods_access = 0.0         # fraction of (wealth-scaled) consumables need met
        self.security = 1.0

    # --- wealth (running total) ----------------------------------------------
    def wealth_per_capita(self):
        return self.wealth / self.amount if self.amount > 0 else 0.0

    def wealth_level(self):
        return get_wealth_level(self.amount, self.wealth)

    def set_wealth(self, amount):
        """Overwrite this tick's wealth (running total). Clamped >= 0; pops never accumulate."""
        self.wealth = max(0.0, amount)

    # --- needs (scale with wealth level: richer pops want & consume more) ---
    def food_need(self):   return food_req[self.wealth_level()] * self.amount
    def goods_need(self):  return goods_req[self.wealth_level()] * self.amount   # consumables demand

    # --- standard of living ---------------------------------------------------
    def standard_of_living(self):
        """SoL from wealth level (mainly), food access, goods access, security. Bounded ~[0,1].
        Drives population growth, unrest, migration, class mobility, treasury contribution."""
        wl = self.wealth_level() / 50.0
        return 0.55 * wl + 0.25 * min(1.0, self.food_access) \
             + 0.10 * min(1.0, self.goods_access) + 0.10 * self.security

    def __repr__(self):
        return (f"Pop({self.pop_type} n={self.amount:.2f} w/c={self.wealth_per_capita():.2f} "
                f"lvl={self.wealth_level()} SoL={self.standard_of_living():.2f})")


# ---------------------------------------------------------------------------
# Location — thin harness wiring land + pops together for one tick.
# (Not the final design; enough to exercise the objects and match the doc's flow.)
# ---------------------------------------------------------------------------
class Location:
    def __init__(self, land_area=10.0, security=1.0, control=1.0, wage_d_crit=1.0, wage_k=-8.0):
        self.land_area = land_area
        self.security = security
        self.control = control
        self.wage_d_crit = wage_d_crit  # labor-pressure falling point for the wage share (lower => wages fall earlier)
        self.wage_k = wage_k
        self.pops = {}                  # pop_type -> Pop
        self.parcels = []               # elite-owned land parcels (cultivated / pastoral / urban)
        self.output = {}                # last-tick produced goods
        self.wage_share = 0.0

    def add_pop(self, pop):       self.pops[pop.pop_type] = pop
    def add_parcel(self, parcel): self.parcels.append(parcel)

    def rural_labor(self):
        """Slaves + Commoners staff the land. (Urbanites are gone; commoners work urban land too.)"""
        return sum(self.pops[t].amount for t in ("Slave", "Commoner") if t in self.pops)

    def elite_opportunities(self, state_elite_opps=0.0):
        """Local (land) opportunities + accessible state opportunities (state pool is a stub arg for now)."""
        return sum(p.elite_opportunities() for p in self.parcels) + state_elite_opps

    def tick(self):
        commoners = self.pops.get("Commoner")
        slaves    = self.pops.get("Slave")
        elites    = self.pops.get("Elite")
        workers   = self.rural_labor()          # slaves + commoners

        # --- labor allocation: split workers across parcels weighted by pay (job pull). ---
        # wage_share depends on assigned workers (circular), so use a location-level share as the weight.
        total_jobs = sum(p.job_capacity() for p in self.parcels)
        loc_wage_share = (get_wage_share(workers, total_jobs, 0.0, k=self.wage_k, d_crit=self.wage_d_crit)
                          if total_jobs > 0 else 0.0)
        self.wage_share = loc_wage_share
        pulls = [p.job_pull(loc_wage_share) for p in self.parcels]
        total_pull = sum(pulls)
        for p, pl in zip(self.parcels, pulls):
            p.workers = workers * (pl / total_pull) if total_pull > 0 else 0.0

        # --- production + wealth distribution (running totals this tick) ---
        totals = {}
        total_wealth = labor_share_wealth = 0.0
        for p in self.parcels:
            for g, amt in p.produce().items():
                totals[g] = totals.get(g, 0.0) + amt
            w_ = p.produce().get("wealth", 0.0)
            total_wealth += w_
            labor_share_wealth += w_ * self.wage_share
        self.output = totals

        # Slaves are assigned first and earn NOTHING (their labor share is confiscated by the owner). With no
        # hard job cap (output saturates), "slaves first" == commoners take the labor pool left after slaves,
        # i.e. the commoner share of the paid labor pool is commoners/(slaves+commoners).
        commoner_frac = (commoners.amount / workers) if (workers > 0 and commoners is not None) else 0.0
        commoner_income = labor_share_wealth * commoner_frac
        elite_income = total_wealth - commoner_income          # surplus + confiscated slave labor share

        if commoners is not None: commoners.set_wealth(commoner_income)
        if elites    is not None: elites.set_wealth(elite_income)
        if slaves    is not None: slaves.set_wealth(0.0)       # slaves receive only subsistence living

        # --- food & consumables access (needs scale with wealth level) ---
        for pop in self.pops.values():
            fneed, gneed = pop.food_need(), pop.goods_need()
            pop.food_access  = (totals.get("food", 0.0) / fneed) if fneed > 0 else 1.0
            pop.goods_access = (totals.get("consumables", 0.0) / gneed) if gneed > 0 else 0.0
            pop.security = self.security

        return {"output": totals, "commoner_income": commoner_income, "elite_income": elite_income,
                "loc_wage_share": loc_wage_share,
                "food": totals.get("food", 0.0), "consumables": totals.get("consumables", 0.0),
                "wealth": total_wealth}


# ---------------------------------------------------------------------------
# Demo / smoke test
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    loc = Location(land_area=10.0, security=1.0)
    loc.add_pop(Pop("Slave", amount=2.0))
    loc.add_pop(Pop("Commoner", amount=6.0))
    loc.add_pop(Pop("Elite", amount=0.1))
    elite = loc.pops["Elite"]
    loc.add_parcel(Parcel(CULTIVATED, area=4.0, owner=elite))
    loc.add_parcel(Parcel(PASTORAL, area=3.0, owner=elite))
    loc.add_parcel(Parcel(URBAN, area=1.0, owner=elite))

    print("Land types:", list(LAND_TYPES))
    print("Parcels:")
    for p in loc.parcels:
        print("  ", p, "| jobs", round(p.job_capacity(), 2), "| land", round(p.land_use(), 2),
              "| elite_opps", round(p.elite_opportunities(), 3))
    print("elite opportunities (land):", round(loc.elite_opportunities(), 3))

    print("\nRunning 3 ticks (wealth is a running total — should be steady, NOT accumulating):")
    for t in range(3):
        r = loc.tick()
        o = r["output"]
        print(f" t{t}: food {o.get('food',0):.2f} consumables {o.get('consumables',0):.2f} "
              f"wealth {r['wealth']:.2f} | wage_share {r['loc_wage_share']:.2f} "
              f"| commoner_w {r['commoner_income']:.2f} elite_w {r['elite_income']:.2f}")
    print("\nPops after (slaves earn 0; their labor share raises elite surplus):")
    for p in loc.pops.values():
        print("  ", p)
